name: CI/CD

on:
  push:
    branch:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0

  deploy:
    name: deploy on Heroku
    runs-on: ubuntu-latest
    needs:
      - lintS
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: BUild and Push
        env:S
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}S
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web